version: "3.8"

services:
  mysql:
    image: mysql:8
    container_name: gas_mysql
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
    ports:
      - "${MYSQL_LOCAL_PORT}:${MYSQL_DOCKER_PORT}"
    volumes:
      - ./db:/var/lib/mysql
      - ./sql/init.sql:/docker-entrypoint-initdb.d/init.sql

  backend:
    build: ./backend
    container_name: gas_backend
    restart: unless-stopped
    env_file: ./.env
    environment:
      - DB_HOST=mysql
      - MYSQL_LOCAL_PORT=${MYSQL_LOCAL_PORT}
      - MYSQL_DATABASE=${MYSQL_DATABASE}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    ports:
      - "3001:3001"
    depends_on:
      - mysql
    volumes:
      - ./backend:/app

  # frontend:
  #   build: ./frontend
  #   container_name: gas_frontend
  #   restart: unless-stopped
  #   ports:
  #     - "3000:80"
  #   depends_on:
  #     - backend
  #   volumes:
  #     - ./frontend:/app

volumes:
  db_data:
