export const candidatesColumns = [
  "Candidate ID",
  "Candidate Name",
  "Course Number",
  "Professor Name",
];

export const assignGraderColumns = [
  "Reassign",
  "Name(Student Id)",
  "Major",
  "Document",
  "Assigned Date",
];

export const courseData = {
  courseNumber: "CS4455",
  courseSection: "004",
  courseName: "CS Project",
  openPosition: 3,
  courseDec: "Algorithm, Java, Dynamic programming",
};

export const graderList = [
  { id: 9944288, name: "John Doe", netId: "jsl20001" },
  { id: 9944298, name: "Kohn Doe", netId: "ksl20001" },
  { id: 9944278, name: "Tohn Doe", netId: "tsl20001" },
];

export const assignGraders = [
  {
    id: 9944278,
    name: "John Doe",
    netId: "jsl20001",
    major: "Computer Science",
    doc: "Resume.pdf",
    AssignedDate: "2024-11-07",
  },
  {
    id: 9944278,
    name: "Kohn Doe",
    netId: "ksl20001",
    major: "Computer Science",
    doc: "Resume.pdf",
    AssignedDate: "2024-11-07",
  },
  {
    id: 9944278,
    name: "Tohn Doe",
    netId: "tsl20001",
    major: "Computer Science",
    doc: "Resume.pdf",
    AssignedDate: "2024-11-07",
  },
];

export const applicationlist = [
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
];

export const courseOptions = [
  {
    id: "4302",
    name: "CS4302 - Intro to Computer Science",
    department: "Computer Science",
    section: "001",
    credits: 3,
    professor: "John Smith",
  },
  {
    id: "4301",
    name: "MATH4301 - Linear Algebra",
    department: "Mathematics",
    section: "002",
    credits: 3,
    professor: "Jane Doe",
  },
  {
    id: "4306",
    name: "PHYS4306 - General Physics I",
    department: "Physics",
    section: "003",
    credits: 4,
    professor: "Michael Newton",
  },
  {
    id: "4251",
    name: "HIST201 - Modern History",
    department: "History",
    section: "004",
    credits: 2,
    professor: "Clover Adams",
  },
];
