export const applicationlist = [
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "John",
    lastName: "Smith",
    name: "Jhon Smith",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 2,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "In progress",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
  {
    id: "9944825",
    firstName: "Jane",
    lastName: "Doe",
    name: "Jane Doe",
    netId: "jsl20001",
    course: "CS4545.004",
    courseName: "CS project",
    position: "Computer Science Grader-Graduation",
    matchCount: 3,
    matchingKeyword: {
      skill: "python",
      major: "Computer Science",
      experience: "2 years",
    },
    status: "Assigned",
    date: "2024-11-07",
    graduationDate: "2026-05-17",
    major: "Computer Science",
    school: "The University of Texas at Dallas",
    year: "masters",
  },
];
